# Generated by Django 3.1.6 on 2021-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
