# Generated by Django 3.1.6 on 2021-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0003_auto_20210207_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='formatted_date',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='formatted_date',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
