# Generated by Django 3.1.6 on 2021-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20210207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
