# Generated by Django 3.1.6 on 2021-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0005_auto_20210207_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
