# Generated by Django 3.1.6 on 2021-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0006_auto_20210208_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='formatted_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='formatted_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
